---

- name: Apt repo is defined
  stat:
    path: /etc/apt/sources.list.d/runner_gitlab-runner.list
  register: apt_repo

- name: Create temporary directory for GitLab repo download
  tempfile:
    state: directory
  register: t
  when: not apt_repo.stat.exists

- name: Download GitLab repo installer
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: "{{ t.path }}/script.deb.sh"
    mode: '0755'
  environment: "{{ proxy_env }}"
  when: not apt_repo.stat.exists

- name: Remove old GitLab repo
  file:
    name: /etc/apt/sources.list.d/runner_gitlab-ci-multi-runner.list
    state: absent

- name: Install GitLab repo
  command: "{{ t.path }}/script.deb.sh"
  args:
    creates: /etc/apt/sources.list.d/runner_gitlab-runner.list
  environment: "{{ proxy_env }}"
  when: not apt_repo.stat.exists
  become: yes

- name: Install GitLab runner
  package:
    name: gitlab-runner
    state: latest
  environment: "{{ proxy_env }}"
  become: yes
