---

- name: RHEL Install GitLab GPG
  rpm_key:
    state: present
    key: https://packages.gitlab.com/gpg.key
  environment: "{{ proxy_env }}"
  become: yes

- name: RHEL Install GitLab dependencies
  package:
    name: "{{ item }}"
    state: present
  environment: "{{ proxy_env }}"
  become: yes
  with_items:
    - pygpgme
    - yum-utils

- name: Remove old repository
  yum_repository:
    name: runner_gitlab-ci-multi-runner
    state: absent
  notify:
    - gitlab_runner yum clean metadata
  become: yes

- name: RHEL Install GitLab Repo
  yum_repository:
    description: GitLab Runner Repo
    name: runner_gitlab-runner
    baseurl: "https://packages.gitlab.com/runner/gitlab-runner/el/{{ ansible_distribution_major_version }}/$basearch"
    repo_gpgcheck: yes
    gpgcheck: no
    gpgkey: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
  notify:
    - gitlab_runner yum makecache
  become: yes

# -10. perfix is required to migrate from the previous package name: gitlab-ci-multi-runner
# Without this prefix, Ansible won't upgrade it.
- name: RHEL Install GitLab runner
  yum:
    name: "gitlab-runner-10.*"
    state: latest
  notify:
    - gitlab_runner service file workaround
  environment: "{{ proxy_env }}"
  become: yes
