---
- name: gitlab_runner yum makecache
  shell:  yum -q makecache -y --disablerepo='*' --enablerepo='runner_gitlab-runner'
  environment: "{{ proxy_env }}"
  become: yes

- name: gitlab_runner yum clean metadata
  shell:  yum clean metadata
  become: yes

# https://gitlab.com/gitlab-org/gitlab-runner/issues/2786
- name:  gitlab_runner service file workaround
  shell: /usr/share/gitlab-runner/post-install
  environment: "{{ proxy_env }}"
  become: yes
